http:
  hostname: "localhost"
  port: "8081"
  
db:
  host: "localhost"
  port: "1521"
  username: "muledemo11"
  password:  "muledemo11"
log:
  msg1 : "....getdb started...."
  msg2 : "....getdb ended...."  
query: 
  allstudents: "select sno,sname,m1,m2 from students"  